"use client"
import Link from "next/link"
import { useState } from "react"
import { createClient } from "@/lib/supabase/client"

const supabase=createClient()
export type StaffPackageItem={id:string;code:string;name:string;service_category:string;included_sessions:number;validity_days:number|null;shareable:boolean;billing_mode:string;active:boolean;standard_price:number|null}
export type StaffPackageStage={id:string;package_id:string;stage_order:number;stage_key:string;label:string;trigger_type:string;trigger_sessions_left:number|null;blocks_new_bookings_when_due:boolean;active:boolean}
export type StaffPackageSnapshot={packages:StaffPackageItem[];stages:StaffPackageStage[]}
function peso(v:number|null){return v==null?"Price not configured":new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(v)}
export default function StaffPackagesPageClient({role,initialSnapshot,initialError}:{role:"staff"|"admin";initialSnapshot:StaffPackageSnapshot;initialError:string|null}){
 const [snapshot,setSnapshot]=useState(initialSnapshot); const [error,setError]=useState<string|null>(initialError); const [saving,setSaving]=useState<string|null>(null)
 async function save(pkg:StaffPackageItem,price:string,active:boolean){setSaving(pkg.id);setError(null);const parsed=price.trim()===""?null:Number(price);if(parsed!==null&&(!Number.isFinite(parsed)||parsed<0)){setSaving(null);return setError("Enter a valid non-negative price or leave it blank.")}const {data,error:e}=await supabase.rpc("admin_update_package_settings",{p_package_id:pkg.id,p_standard_price:parsed,p_active:active});setSaving(null);if(e)return setError(e.message);setSnapshot(data as StaffPackageSnapshot)}
 return <main className="min-h-screen bg-[#020b1c] px-4 py-6 text-white"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff9b54]">BearFit Staff</p><h1 className="text-3xl font-black">Package Settings</h1><p className="mt-1 text-sm text-white/45">Prices are guidance. Session rules stay protected.</p></div><div className="flex gap-2"><Link href="/staff/schedule" className="rounded-full bg-white/10 px-4 py-2 text-sm">Schedule</Link><Link href="/payments" className="rounded-full bg-[#ff7a1a] px-4 py-2 text-sm font-bold">Payments</Link></div></header>{error&&<div className="mt-4 rounded-2xl bg-red-500/10 p-4 text-red-200">{error}</div>}<section className="mt-6 grid gap-4 lg:grid-cols-2">{snapshot.packages.map(pkg=><PackageCard key={pkg.id} pkg={pkg} stages={snapshot.stages.filter(s=>s.package_id===pkg.id)} canEdit={role==="admin"&&pkg.code!=="LEGACY_FITNESS"} saving={saving===pkg.id} onSave={save}/>)}</section></div></main>
}
function PackageCard({pkg,stages,canEdit,saving,onSave}:{pkg:StaffPackageItem;stages:StaffPackageStage[];canEdit:boolean;saving:boolean;onSave:(pkg:StaffPackageItem,price:string,active:boolean)=>void}){const [price,setPrice]=useState(pkg.standard_price?.toString()??"");const [active,setActive]=useState(pkg.active);return <article className="rounded-[24px] border border-white/[.07] bg-[#171717] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-white/35">{pkg.code}</p><h2 className="mt-1 text-xl font-black">{pkg.name}</h2><p className="mt-1 text-sm text-white/45">{pkg.service_category}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${active?"bg-emerald-500/15 text-emerald-300":"bg-white/10 text-white/45"}`}>{active?"Active":"Inactive"}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Meta label="Included sessions" value={String(pkg.included_sessions)}/><Meta label="Validity" value={pkg.validity_days?`${pkg.validity_days} days`:"No fixed validity"}/><Meta label="Billing mode" value={pkg.billing_mode}/><Meta label="Shareable" value={pkg.shareable?"Yes":"No"}/></div><div className="mt-4 rounded-2xl bg-white/[.04] p-4"><p className="text-xs font-bold uppercase tracking-[.13em] text-white/35">Payment stages</p>{stages.length?stages.map(s=><p key={s.id} className="mt-2 text-sm text-white/60">{s.stage_order}. {s.label}{s.trigger_sessions_left!==null?` · ${s.trigger_sessions_left} left`:""}</p>):<p className="mt-2 text-sm text-white/40">No staged payments.</p>}</div><label className="mt-4 block"><span className="text-xs font-bold uppercase tracking-[.13em] text-white/45">Standard price</span><input disabled={!canEdit} value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price not configured" className="mt-2 w-full rounded-xl border border-white/10 bg-[#222] px-4 py-3 disabled:opacity-50"/><p className="mt-1 text-xs text-white/35">Current: {peso(pkg.standard_price)}</p></label><label className="mt-4 flex items-center gap-3 text-sm"><input disabled={!canEdit} type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active package</label>{canEdit?<button disabled={saving} onClick={()=>onSave(pkg,price,active)} className="mt-4 w-full rounded-xl bg-[#ff7a1a] px-4 py-3 font-bold disabled:opacity-50">{saving?"Saving…":"Save package settings"}</button>:<p className="mt-4 text-xs text-white/35">Admin access required to change package settings.</p>}</article>}
function Meta({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white/[.04] p-3"><p className="text-[10px] uppercase tracking-[.12em] text-white/35">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
